{{- range .Values.services }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "Sunburn.fullname" $ }}
  labels:
    {{- include "Sunburn.labels" $ | nindent 4 }}
spec:
  type: {{ .service.type }}
  ports:
    - port: {{ .service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "Sunburn.selectorLabels" $ | nindent 4 }}
---
{{- end }}
